#!/usr/bin/env python3
#-*- coding: Utf-8 -*-
from math import factorial
#Some Functions
CS = ['abcefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ','0987654321','*!$?@&']
CS2 = []

#Export this part as a function (thanks to google for that function)
def human_read(num, suffix='B'):
    for unit in ['', 'Ki', 'Mi', 'Gi', 'Ti', 'Pi', 'Ei', 'Zi']:
        if abs(num) < 1024.0:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= 1024.0
    return "%.1f%s%s" % (num, 'Yi', suffix)

#Export this part as a function (thanks to google for that function)
def combination(n ,k):
    numerator = factorial(n)
    denominator = (factorial(k)*factorial(n-k))
    answer = numerator/denominator
    return answer

#Some variables
lower = (26)
upper = (26)
numbers = (10)
specials = (10)
a = 0
#Questions time
l = input('Lower case ? [y/n]')
if l == 'y':
    print('Ok Lower')
    a = lower
    print(a)
    CS2=(CS[0])


l = input('Upper case ? [y/n]')
if l == 'y':
    print('Ok upper')
    a = (a+upper)
    print(a)
    CS2=CS2+(CS[1])

l = input('Numbers ? [y/n]')
if l == 'y':
    print('Ok Numbers')
    a = (a+numbers)
    print(a)
    CS2=CS2+(CS[2])

l = input('Most common special characters (*!$?@&) ? [y/n]')
if l == 'y':
    print('Ok Special')
    a = (a+specials)
    print(a)
    CS2=CS2+(CS[3])

print ("The charset is :")
print (CS)
print (80*'-')
b = int(input("Word length : "))

re=int((combination(a,b)))
print ('Number of passwords')
print ("{:,}".format(re))
print ("Estimated file size")
size = (re*4)
print(human_read(size))
